### ISSUE TITLE
Configurable Plantuml server url

### ISSUE THREAD

**Issue by bharatrajagopalan** [Mogeko/gatsby-remark-plantuml-lite#13]
Can we get the ability to configure the plantuml server end point? 

Rather than calling the plantuml server, we may want to call a server that is running either locally or on the intranet e.g. using the plantuml pico webserver (https://plantuml.com/picoweb)

**Comment by Mogeko** [comment]
This is a good idea!  And this seems very easy to implement.


I will add this feature in the next version.
